name: Test

on:  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install '.[dev]'
          pip list
      - run: mypy --install-types --non-interactive
