name: Docker

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
  push:
    branches: [main, "release/*", "docker/*"]
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-20.04
    # only on releases
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
    strategy:
      fail-fast: false
      matrix:
        # initially building only the latest supported configuration
        python_version: ["3.9"]
        pytorch_version: ["1.11"]
        cust_base: ["cu11.3-"]
        pl_version: ["1.6"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get release version
        id: get_version
        run: echo "::set-output name=RELEASE_VERSION::$(echo ${GITHUB_REF##*/})"

      - name: Publish Latest to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: dockers/release/Dockerfile
          build-args: |
            PYTHON_VERSION=${{ matrix.python_version }}
            PYTORCH_VERSION=${{ matrix.pytorch_version }}
            CUST_BASE=${{ matrix.cust_base }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/finetuning-scheduler:fts${{ steps.get_version.outputs.RELEASE_VERSION }}-${{ matrix.cust_base }}py${{ matrix.python_version }}-pt${{ matrix.pytorch_version }}-pl{{ matrix.pl_version }},${{ secrets.DOCKERHUB_USERNAME }}/finetuning-scheduler:test
        timeout-minutes: 55
